export default {
  0: '$(code)', // "File",
  1: '$(book)', // "Module",
  2: '$(three-bars)', // "Namespace",
  3: '$(package)', // "Package",
  4: '$(verified)', // "Class",
  5: '$(pulse)', // "Method",
  6: '$(plus)', // "Property",
  7: '$(pin)', // "Field",
  8: '$(plug)', // "Constructor",
  9: '$(organization-filled)', // "Enum",
  10: '$(lock)', // "Interface",
  11: '$(mention)', // "Function",
  12: '$(primitive-dot)', // "Variable",
  13: '$(primitive-square)', // "Constant",
  14: '$(quote)', // "String",
  15: '$(list-ordered)', // "Number",
  16: '$(law)', // "Boolean",
  17: '$(kebab-horizontal)', // "Array",
  18: '$(kebab-vertica)', // "Object",
  19: '$(key)', // "Key",
  20: '$(x)', // "Null",
  21: '$(person-filled)', // "EnumMember",
  22: '$(kebab-vertical)', // "Struct",
  23: '$(watch)', // "Event",
  24: '$(terminal)', // "Operator",
  25: '$(zap)', // "TypeParameter"
};
